[project]
name = "bec-gp-code"
version = "0.1.0"
description = "Gross-Pitaevskii equation solver for multi-component Bose-Einstein condensate"
authors = ["Federico Serrano"]

[workspace]
channels = ["conda-forge"]
name = "bec-gp-code"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "pytest"
format = "black src/"


[dependencies]
python = "3.12.3.*"
numpy = ">=2.4.2,<3"
scipy = ">=1.17.0,<2"
matplotlib = ">=3.10.8,<4"

[feature.dev.dependencies]
pytest = "*"
black = ">=26.1.0,<27"

[environments]
default = []
dev = ["dev"]
